---
output:
  word_document:
    reference_docx: ../MPFF report template v1.1.dotx
---


```{r setup, include=FALSE}

# print settings
options(max.print=999999)
options(dplyr.summarise.inform = FALSE)

knitr::opts_chunk$set(echo = FALSE,	message = FALSE,	warning = FALSE,	comment = "",	crop = TRUE )
knitr::opts_chunk$set(fig.width=10) 

# Reset lists
rm(list=ls())

# Open relevant packages 
library(tidyverse)     # combined package of dplyr, tidyr, ggplot, readr, purrr and tibble
library(readxl)        # excel reader from hadley
library(writexl)       # write excel files
library(zoo)           # manipulating data
library(lubridate)     # date functions      (this is part of tidyverse, but needs to be loaded separately)
library(stringr)       # string manipulation (this is part of tidyverse, but needs to be loaded separately)
library(sf)            # simple features
library(tidygeocoder)  # finding positions for harbours
library(sqldf)         # look up values within a range

# source("../gisland/r/geo_inside.R")
source("../r/FLYSHOOT utils.R")

onedrive   = "C:/Users/MartinPastoors/Martin Pastoors/FLYSHOOT - General/rdata"
tripdir    = "C:/Users/MartinPastoors/Martin Pastoors/FLYSHOOT - General/tripdata/SL9"

# load spatial datasets -------------------------
spatialdir = "C:/DATA/RDATA"
load(file.path(spatialdir, "fao_sf.RData"))
load(file.path(spatialdir, "rect_sf.RData"))
load(file.path(spatialdir, "world_mr_sf.RData"))
load(file.path(spatialdir, "world_mr_df.RData"))
rect_df <-
  loadRData(file.path(spatialdir, "rect_df.RData")) %>% 
  rename(rect=ICESNAME) %>% 
  group_by(rect) %>% 
  filter(row_number() ==1) %>% 
  dplyr::select(rect, lon=long, lat)

# ----------------------------------------------------------------------------
# read the pefa elog data per trek
# ----------------------------------------------------------------------------

filelist <- list.files(
  path=file.path(tripdir),
  pattern="elog_pefa_per_trek",
  full.names = TRUE)

if(!is_empty(filelist)){
  
  elog_trek <- data.frame(stringsAsFactors = FALSE)
  
  i <- 1
  for (i in 1:length(filelist)) {
    
    myvessel <- stringr::word(basename(filelist[i]), 1, sep=" ") %>%
      unlist()     
    mytrip <- stringr::word(basename(filelist[i]), 2, sep=" ") %>%
      gsub("_","",.) %>%
      unlist()     
    
    print(paste("elog pefa per trek", myvessel, mytrip))
    
    # TO DO: SET HAULID TO START AT 1 (haulid-min(haulid))
    
    e  <-
      readxl::read_excel(filelist[i], col_names=TRUE, col_types="text",
                         .name_repair =  ~make.names(., unique = TRUE))  %>% 
      data.frame() %>% 
      lowcase() %>% 
      rename(rect = icesrectangle) %>% 
      # rename(vessel = vesselnumber) %>% 
      # mutate(vessel = gsub(" ","", vessel)) %>% 
      # mutate(vessel = ifelse(vessel=="SL09", "SL9","")) %>% 
      
      rename(lat = latitude) %>% 
      rename(lon = longitude) %>% 
      
      {if(any(grepl("haulid",names(.)))) {rename(., haul = haulid)} else{.}} %>% 
      
      mutate(across (any_of(c("boxes", "meshsize", "haul")),
                     as.integer)) %>%
      mutate(across (c("catchdate", "departuredate","arrivaldate", "auctiondate", "weight", "lat", "lon", "conversionfactor"),
                     as.numeric)) %>%
      # mutate(across(c("catchdate"),
      #               ~as.POSIXct(. * (60*60*24), origin="1899-12-30", tz="UTC"))) %>% 
      mutate(across (c("catchdate", "departuredate","arrivaldate", "auctiondate"), 
                     ~excel_timezone_to_utc(., timezone="UTC"))) %>% 
      
      mutate(date   = as.Date(catchdate)) %>% 
      
      {if(any(grepl("haul",names(.)))) {mutate(., haul = haul - min(haul, na.rm=TRUE)+1)} else{.}} %>% 
      # dplyr::select(-catchdate) %>% 
      
      mutate(
        year       = lubridate::year(date),
        quarter    = lubridate::quarter(date),
        month      = lubridate::month(date),
        week       = lubridate::week(date),
        yday       = lubridate::yday(date)) %>% 
      
      mutate(vessel = myvessel) %>% 
      mutate(trip = mytrip) %>% 
      
      # Keep only the first lat long observation of each haul
      group_by(vessel, trip, haul) %>% 
      mutate(
        lat2 = first(na.omit(lat)),
        lon2 = first(na.omit(lon))
      ) %>%
      mutate(across (c("lat2","lon2"),    ~zoo::na.locf(.))) %>%
      ungroup()
      
    elog_trek <- bind_rows(elog_trek, e)

  } # end of pefa elog for loop
  
} # end of not empty filelist


# ----------------------------------------------------------------------------
# read the treklijst data
# ----------------------------------------------------------------------------

filelist <- list.files(
  path=file.path(tripdir),
  pattern="treklijst",
  full.names = TRUE)

i <- 23
if(!is_empty(filelist)){
  
  hh <- data.frame(stringsAsFactors = FALSE)
  
  for (i in 1:length(filelist)) {
  
  # vessel and trip
    myvessel <- stringr::word(basename(filelist[i]), 1, sep=" ")

    mytrip <- stringr::word(basename(filelist[i]), 2, sep=" ") %>%
      gsub("_","",.) %>%
      unlist()     

    if (paste(myvessel, mytrip) %in% paste(elog_trek$vessel, elog_trek$trip)) {
    
      print(paste("treklijst", myvessel, mytrip))

      r <-
        readxl::read_excel(filelist[i],
                   sheet = "Haul",  col_names=TRUE, col_types="text",
                   .name_repair =  ~make.names(., unique = TRUE))  %>% 
        data.frame() %>% 
        lowcase() %>% 
        summarise(
          ndate = max(
            sum(!is.na(date)),
            sum(!is.na(tijdeindehalen)),
            sum(!is.na(tijdbeginuitzetten)),
            sum(!is.na(tijdeindeuitzetten)),
            sum(!is.na(shootlat)),
            sum(!is.na(shootlong)),
            sum(!is.na(waterdepth)))
        ) %>% 
        as.integer()
    
    # read the haul data
    h <-
      readxl::read_excel(filelist[i],
                         sheet = "Haul",  col_names=TRUE, col_types="text",
                         .name_repair =  ~make.names(., unique = TRUE))  %>% 
      data.frame() %>% 
      lowcase() %>% 
      filter(!is.na(vessel), row_number() <= r ) %>% 
      mutate(timezone = case_when(
        timezone == "CET"   ~ "Europe/Amsterdam", 
        timezone == "UTC+1" ~ "Europe/Amsterdam", 
        timezone == "UTC-5" ~ "America/Santiago",
        is.na(timezone)     ~ "UTC",    
        TRUE                ~ timezone) ) %>% 
      mutate(date   = as.Date(as.integer(date), origin="1899-12-30", tz=timezone)) %>% 
        
      
      dplyr::rename(
        shoottime    = berekentijdbeginuitzetten,
        shoottime2   = berekentijdeindeuitzetten,
        haultime     = berekentijdeindehalen
      )  %>%  
          
      mutate(across (c("shoottime", "shoottime2", "haultime"), 
                     as.numeric)) %>%
      
      mutate(across (c("shoottime","shoottime2", "haultime"),
                     ~calculate_time(.))) %>%
      
      mutate( 
        shoottime  = ifelse(!is.na(shoottime), date + shoottime, NA),
        shoottime  = as_datetime(shoottime),
        shoottime2 = ifelse(!is.na(shoottime2), date + shoottime2, NA),
        shoottime2 = as_datetime(shoottime2),
        haultime   = ifelse(!is.na(haultime), date + haultime, NA),
        haultime   = as_datetime(haultime)
      ) %>%
          
      # add haultime if missing
      mutate(
        haultime = ifelse(is.na(haultime) & !is.na(shoottime), 
                          shoottime+lubridate::hm("1:20"), 
                          haultime),
        haultime = lubridate::as_datetime(haultime)
      ) %>% 
      
      # add haultime and shoottime if missing and shoottime2 is available
      mutate(
        test     = ifelse(is.na(haultime) & is.na(shoottime) & !is.na(shoottime2),
                          TRUE, FALSE),
        shoottime = ifelse(test, 
                           shoottime2-lubridate::hm("0:40"), 
                           shoottime),
        shoottime = lubridate::as_datetime(shoottime),
        
        haultime = ifelse(test, 
                          shoottime2+lubridate::hm("0:40"), 
                          haultime),
        haultime = lubridate::as_datetime(haultime)
      ) %>% 
      
      # add next haul time  
      group_by(vessel, trip) %>% 
      mutate(nexthaultime = lead(haultime)) %>% 
      mutate(nexthaultime = ifelse(is.na(nexthaultime), lubridate::dmy_hm("31/12/2023 23:59"), nexthaultime)) %>% 
      mutate(nexthaultime = as_datetime(nexthaultime)) %>% 
          
          
      dplyr::rename(
        windforce     = windforcebft,
        catchheight   = catchhoogtevangstincm, 
        boxtype       = boxvolledigofkleinvk, 
        landingweight = marktwaardigeviskg,
        totalcatch    = totalevangstkgberekend, 
        bycatchperc   = percentagebijvangst, 
        dateembarked = dateembarkedutcdate,
        portembarked = portofembarkation,
        datedisembarked = datedisembarkedutcdate,
        portdisembarked = portofdisembarkation,
        cablelength   = cablelengthm, 
        cablethickness= cablethicknessmm,
        lengthgroundrope= lengthgroundropem,
        escapepanel   = escapepanelyn         
      )  %>%  
      
      # remove shootns or shootew if empty position
      mutate(shootns = ifelse(is.na(shootlat), NA, shootns)) %>% 
      mutate(shootew = ifelse(is.na(shootlong), NA, shootew)) %>% 
      
      # fill up empty cells
      mutate(across (c("date","shootlat","shootns", "shootlong", "shootew"),    ~zoo::na.locf(.))) %>% 
      {if(!all(is.na(.$winddirection))) { mutate(., across (c("winddirection"), ~zoo::na.locf(.)))} else {.}} %>%
      {if(!all(is.na(.$windforce)))     { mutate(., across (c("windforce"),     ~zoo::na.locf(.)))} else {.}} %>%
      
      mutate(across (c("shootew", "shootns"), 
                     toupper)) %>% 
      mutate(vessel = toupper(vessel)) %>% 
      mutate(across (c("haul", "meshsize", "windforce", "waterdepth",
                       "catchheight", "dateembarked","datedisembarked"), 
                     as.integer)) %>% 
      mutate(across (c("waterdepth","vertopening", "landingweight", "totalcatch"), 
                     as.numeric)) %>%
      
      # mutate(date   = as.Date(date, origin="1899-12-30" , tz=unique(timezone))) %>% 
      mutate(dateembarked   = as.Date(dateembarked, origin="1899-12-30" , tz=unique(timezone))) %>% 
      mutate(datedisembarked   = as.Date(datedisembarked, origin="1899-12-30" , tz=unique(timezone))) %>% 
      

      mutate(
        year       = lubridate::year(date),
        quarter    = lubridate::quarter(date),
        month      = lubridate::month(date),
        week       = lubridate::week(date),
        yday       = lubridate::yday(date)) %>%
      dplyr::select(-timezone) %>%
      
      # calculate haul duration: haul_time-shoot_time*24 
      mutate(duration   = as.numeric(as.duration(shoottime %--% haultime))/3600 ) %>% 
      
      # calculate positions
      mutate(
        lon = calculate_position_from_strings(shootlat, shootns, shootlong, shootew)$lon,
        lat = calculate_position_from_strings(shootlat, shootns, shootlong, shootew)$lat
      )  %>% 
      
      # wind directions
      mutate(
        winddirection = toupper(winddirection),
        winddirection = gsub("Z","S",winddirection),
        winddirection = gsub("O","E",winddirection)
      ) %>% 
      
      ungroup() %>% 
      dplyr::select(
        vessel, trip, haul, date, shoottime, shoottime2, haultime, nexthaultime,
        lat, lon, 
        winddirection, windforce, waterdepth,
        catchheight, boxtype, landingweight, totalcatch,
        bycatchperc, skipper, dateembarked, portembarked,
        datedisembarked, portdisembarked, gear, meshsize, vertopening,
        cablelength, cablethickness, lengthgroundrope, escapepanel,
        duration, year, quarter, month, yday
      ) 
      
      # calculate FAO areas  
      h_fao <- 
        h %>%
        drop_na(lat, lon) %>% 
        sf::st_as_sf(coords = c("lon", "lat"), crs = 4326, stringsAsFactors = FALSE, remove = TRUE) %>% 
        sf::st_join(., fao_sf, join = st_within) %>% 
        sf::st_drop_geometry() %>% 
        dplyr::select(vessel, trip, haul, F_LEVEL, F_CODE) %>%
        mutate(F_LEVEL = tolower(F_LEVEL)) %>% 
        mutate(F_LEVEL = ifelse(F_LEVEL=="major", "area", F_LEVEL)) %>% 
        tidyr::pivot_wider(names_from = F_LEVEL, values_from = F_CODE)
      
      # calculate ICES rectangles
      h_rect <- 
        h %>%
        drop_na(lat, lon) %>% 
        sf::st_as_sf(coords = c("lon", "lat"), crs = 4326, stringsAsFactors = FALSE, remove = TRUE) %>% 
        sf::st_join(., rect_sf, join = st_within) %>% 
        sf::st_drop_geometry() %>% 
        dplyr::select(vessel, trip, haul, rect=ICESNAME) 
      
      h <- 
        left_join(h, h_fao,  by=c("vessel","trip","haul")) %>% 
        left_join(., h_rect, by=c("vessel","trip","haul"))
      
      hh <- bind_rows(hh, h)

    } # end of if statement
      
  } # end of treklijst for loop
  
} # end of not empty filelist

# haul <- haul %>% filter(vessel != "SCH135")  



xmin <- floor  (min(hh$lon, na.rm=TRUE))
xmax <- ceiling(max(hh$lon, na.rm=TRUE))+1
ymin <- floor  (2*min(hh$lat, na.rm=TRUE))/2
ymax <- ceiling(2*max(hh$lat, na.rm=TRUE))/2


```


**FLYSHOOT vergelijking PEFA exports**

By: Martin Pastoors

Vergelijking trekposities vanuit treklijst (handmatig ingevuld) en gekoppelde GPS-Marelec-Elog (PEFA) [RAW]. 

```{r, echo=FALSE, message=FALSE, warning=FALSE, comment=NA, fig.asp=0.6}



elog_trek %>%
  dplyr::filter(paste(vessel, trip) %in% paste(hh$vessel, hh$trip)) %>% 
  
  ggplot() +
  theme_publication() +
  coord_quickmap(xlim=c(xmin,xmax) , ylim=c(ymin, ymax)) +
  geom_polygon(data=world_mr_df, aes(x=long, y=lat, group=group), fill = "grey75") +
  
  geom_point(aes(x=lon, y=lat, colour=trip), alpha = 0.5) +
  geom_jitter(data=hh,
             aes(x=lon, y=lat), 
             size=1, shape=3, width=0.05, height=0.025) +

  scale_x_continuous(breaks = seq(floor(xmin), ceiling(xmax), 1)) +
  scale_y_continuous(breaks = seq(floor(2*ymin)/2, ceiling(2*ymax)/2, 0.5)) +
  facet_wrap(~date, ncol=6)


```

\newpage

Vergelijking trekposities vanuit treklijst (handmatig ingevuld) en gekoppelde GPS-Marelec-Elog (PEFA) [ONLY FIRST OBS BY HAUL]. 

```{r, echo=FALSE, message=FALSE, warning=FALSE, comment=NA, fig.asp=0.6}


elog_trek %>%
  dplyr::filter(paste(vessel, trip) %in% paste(hh$vessel, hh$trip)) %>% 
  
  ggplot() +
  theme_publication() +
  coord_quickmap(xlim=c(xmin,xmax) , ylim=c(ymin, ymax)) +
  geom_polygon(data=world_mr_df, aes(x=long, y=lat, group=group), fill = "grey75") +
  
  geom_point(aes(x=lon2, y=lat2, colour=trip), alpha = 0.5) +
  geom_jitter(data=hh,
             aes(x=lon, y=lat), 
             size=1, shape=3, width=0.05, height=0.025) +

  scale_x_continuous(breaks = seq(floor(xmin), ceiling(xmax), 1)) +
  scale_y_continuous(breaks = seq(floor(2*ymin)/2, ceiling(2*ymax)/2, 0.5)) +
  facet_wrap(~date, ncol=6)


```

